# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-01 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0016_savedformdataentry_savedformwizarddataentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedformdataentry',
            name='form_entry',
        ),
        migrations.RemoveField(
            model_name='savedformdataentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savedformwizarddataentry',
            name='form_wizard_entry',
        ),
        migrations.RemoveField(
            model_name='savedformwizarddataentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='SavedFormDataEntry',
        ),
        migrations.DeleteModel(
            name='SavedFormWizardDataEntry',
        ),
    ]
