# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-03 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('fobi', '0017_auto_20180501_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile')),
            ],
        ),
    ]
