# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-04 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('fobi', '0018_approvers'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='title2',
            field=models.CharField(blank=True, help_text='Shown in templates if available.', max_length=255, null=True, verbose_name='Title-ext'),
        ),
        migrations.RemoveField(
            model_name='approvers',
            name='appr',
        ),
        migrations.AddField(
            model_name='approvers',
            name='appr',
            field=models.ManyToManyField(to='core.UserProfile'),
        ),
    ]
