# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-04 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('fobi', '0019_auto_20180704_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formentry',
            name='title2',
        ),
        migrations.AddField(
            model_name='formentry',
            name='approvers',
            field=models.ManyToManyField(blank=True, to='core.UserProfile', verbose_name='Approvers'),
        ),
    ]
