# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-09 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0020_auto_20180704_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvers',
            name='appr',
        ),
        migrations.DeleteModel(
            name='Approvers',
        ),
    ]
