# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-14 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fobi', '0021_auto_20180709_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='submitted_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuck', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
