# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-14 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fobi_contrib_plugins_form_handlers_db_store', '0005_savedformdataentry_disapproved'),
        ('fobi', '0022_auto_20180715_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formentry',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='formentry',
            name='entry_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuck', to='fobi_contrib_plugins_form_handlers_db_store.SavedFormDataEntry', verbose_name='User'),
        ),
    ]
