# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-25 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpletickets', '0003_auto_20150830_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(default='...', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolution_text',
            field=models.TextField(default='', verbose_name='Resolution text'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (5, 'important'), (8, 'very important'), (9, 'Critical')], default=3),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.IntegerField(choices=[(1, 'new'), (2, 'assigned'), (5, 'in progress'), (8, 'solved'), (9, 'closed')], default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.IntegerField(choices=[(1, 'Inform about an error'), (2, 'Problem'), (8, 'Propose a sugestion'), (9, 'Others')], default=2),
        ),
    ]
