# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-30 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0017_auto_20180501_1142'),
        ('core', '0001_initial'),
        ('fobi_contrib_plugins_form_handlers_db_store', '0003_savedformdataentry_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=160)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile')),
                ('form_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fobi.FormEntry', verbose_name='Form')),
            ],
        ),
    ]
