# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-12 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi_contrib_plugins_form_handlers_db_store', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedformdataentry',
            name='disapproved',
            field=models.BooleanField(default=False),
        ),
    ]
