# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-14 23:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fobi_contrib_plugins_form_handlers_db_store', '0005_savedformdataentry_disapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedformdataentry',
            name='submitted_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
