# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-14 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi_contrib_plugins_form_handlers_db_store', '0007_savedformdataentry_mykey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedformdataentry',
            name='mykey',
        ),
        migrations.AddField(
            model_name='savedformdataentry',
            name='application_id',
            field=models.CharField(default='8aqF7w2RcH', max_length=6, null=True),
        ),
    ]
