# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-14 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi_contrib_plugins_form_handlers_db_store', '0008_auto_20180715_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedformdataentry',
            name='application_id',
            field=models.CharField(default='YEEZADz6nu', max_length=6),
        ),
    ]
