# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi_contrib_plugins_form_handlers_db_store', '0009_auto_20180715_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='ident',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedformdataentry',
            name='application_id',
            field=models.CharField(default='RFf5VGnRxy', max_length=6),
        ),
    ]
