# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-22 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi_contrib_plugins_form_handlers_db_store', '0010_auto_20180723_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedformdataentry',
            name='application_id',
            field=models.CharField(default='WVUYU4pLZh', max_length=6),
        ),
    ]
