# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-25 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi_contrib_plugins_form_handlers_db_store', '0012_auto_20180725_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedformdataentry',
            name='application_id',
            field=models.CharField(default='aRMSATxZ4V', max_length=6),
        ),
    ]
