# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-25 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fobi_contrib_plugins_form_handlers_db_store', '0013_auto_20180725_2110'),
        ('fobi_contrib_plugins_form_handlers_db_store', '0011_auto_20180725_2018'),
    ]

    operations = [
    ]
