# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-26 05:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fobi', '0023_auto_20180715_0428'),
        ('fobi_contrib_plugins_form_handlers_db_store', '0015_auto_20180725_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ManyToManyField(blank=True, related_name='approved_by', to=settings.AUTH_USER_MODEL, verbose_name='approvers')),
                ('disapproved_by', models.ManyToManyField(blank=True, related_name='disapproved_by', to=settings.AUTH_USER_MODEL, verbose_name='disapprovers')),
                ('form_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fobi.FormEntry', verbose_name='Form')),
            ],
        ),
        migrations.AlterField(
            model_name='savedformdataentry',
            name='application_id',
            field=models.CharField(default='KCdakbKfyL', max_length=6),
        ),
    ]
