# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-26 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fobi_contrib_plugins_form_handlers_db_store', '0019_auto_20180726_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvals',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='disapproved_by',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='form_entry',
        ),
        migrations.AddField(
            model_name='savedformdataentry',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='approved_by', to=settings.AUTH_USER_MODEL, verbose_name='approvers'),
        ),
        migrations.AddField(
            model_name='savedformdataentry',
            name='disapproved_by',
            field=models.ManyToManyField(blank=True, related_name='disapproved_by', to=settings.AUTH_USER_MODEL, verbose_name='disapprovers'),
        ),
        migrations.AlterField(
            model_name='savedformdataentry',
            name='application_id',
            field=models.CharField(default='bQVDFwPgYZ', max_length=6),
        ),
        migrations.DeleteModel(
            name='Approvals',
        ),
    ]
