# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-26 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi_contrib_plugins_form_handlers_db_store', '0020_auto_20180726_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedformdataentry',
            name='application_id',
            field=models.CharField(default='CnVqHQkzPX', max_length=6),
        ),
        migrations.AlterField(
            model_name='savedformdataentry',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='approved_by', to='core.UserProfile', verbose_name='approvers'),
        ),
        migrations.AlterField(
            model_name='savedformdataentry',
            name='disapproved_by',
            field=models.ManyToManyField(blank=True, related_name='disapproved_by', to='core.UserProfile', verbose_name='disapprovers'),
        ),
    ]
