# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi_contrib_plugins_form_handlers_db_store', '0023_auto_20180801_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedformdataentry',
            name='application_id',
            field=models.CharField(default='uujsQVRnXE', max_length=6),
        ),
        migrations.AlterField(
            model_name='savedformdataentry',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='approved_by', to='core.UserProfile'),
        ),
        migrations.AlterField(
            model_name='savedformdataentry',
            name='disapproved_by',
            field=models.ManyToManyField(blank=True, related_name='disapproved_by', to='core.UserProfile'),
        ),
    ]
