# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 05:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi_contrib_plugins_form_handlers_db_store', '0024_auto_20180803_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedformdataentry',
            name='application_id',
            field=models.CharField(default='mygpDAWuYQ', max_length=6),
        ),
        migrations.AlterField(
            model_name='savedformdataentry',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedformdataentry',
            name='disapproved_by',
            field=models.ManyToManyField(blank=True, related_name='disapproved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
