# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi_contrib_plugins_form_handlers_db_store', '0025_auto_20180803_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedformdataentry',
            name='application_id',
            field=models.CharField(default='xX7ScLQLUJ', max_length=6),
        ),
    ]
