# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-14 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_document_executive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='executive',
        ),
    ]
