# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-26 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_auto_20180726_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
